name: Build all subject PDFs and release them

# Feel free to increment this counter in your attempts to do things
# the smart way instead of the easy way.
#
# total_hours_wasted = 17

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"
  workflow_dispatch:

jobs:
  # zjištění všech složek předmětů
  listOfDirectories:
    runs-on: ubuntu-latest

    outputs:
      # aktuálních složek pro vytvoření jobs matrix předmětů
      dir: ${{ steps.set-dirs.outputs.dir }}

    steps:
      # naklonování repa
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prepare list of directories for jobs
        # název výstupu
        id: set-dirs

        # vypis všech dir | odstranění template/ dir | odstranění prázdného řádku po template/dir
        # | odstranění všech speciálních znaků | rozdělení na json data pro matrix build
        run: echo "::set-output name=dir::$(ls -d */ | sed "s/template\///" | sed "/^$/d" |
         tr -dc '[:alnum:]\n\r-' | jq -R -s -c 'split("\n")[:-1]')"

  # build všech předmětů
  subjects:
    runs-on: ubuntu-latest
    needs: listOfDirectories

    # vytvoření samostatného jobu pro každý předmět
    strategy:
      matrix:
        dir: ${{ fromJson(needs.listOfDirectories.outputs.dir) }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # kompilace
      - name: Build ${{ matrix.dir }}
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          working_directory: ${{ matrix.dir }}
          root_file: main.tex

      # nahrání pro pozdější stáhnutí
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # název zip souboru se specifickým jméne předmětu
          name: ${{ matrix.dir }}
          # co se má uložit do zip souboru
          path: ${{ matrix.dir }}/main.pdf

  # vytvoření prázdného releasu
  release:
    runs-on: ubuntu-latest
    needs: subjects

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Create tag
      id: create_tag
      run: |
        tag=build-$(date +%Y%m%d-%H%M%S)
        echo "::set-output name=tag::$tag"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false

  # přidání jednotlivých pdf předmětů do releasu
  addSubjects:
    runs-on: ubuntu-latest
    # potřeba listOfDirectories pro vytvoření jobs matrix
    needs: [ release, listOfDirectories ]

    # vytvoření samostatného jobu pro každý předmět
    strategy:
      matrix:
        dir: ${{ fromJson(needs.listOfDirectories.outputs.dir) }}

    steps:
    - uses: actions/checkout@v2

    # stažení dříve nahráneho zip souboru v subjects jobu
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.dir }}
        path: ${{ matrix.dir }}

    # přidání do releasu
    - name: Upload artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        # cesta k souboru
        asset_path: ./${{ matrix.dir }}/main.pdf
        # název v releasu
        asset_name: ${{ matrix.dir }}.pdf
        asset_content_type: application/pdf
